name: Deploy to Strato

on:
  push:
    branches:
      - main  # oder main, je nachdem wie dein Branch heißt

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ssh.strato.de
          username: ${{ secrets.sftp_GitHubDeploy }}   # ⬅️ Nur Buchstaben/Zahlen/Unterstriche
          password: ${{ secrets.zaxtewzamPyf1nunsa }}
          protocol: sftp                          # ⬅️ GANZ WICHTIG für Strato
          port: 22
          local-dir: ./                           # ⬅️ Wo deine Dateien im Repo liegen
          server-dir: /htdocs/                    # ⬅️ Zielordner bei Strato (Standard)
