name: Deploy to Strato via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Upload files to Strato via SFTP
      run: |
        sshpass -p "${{ secrets.SFTP_PASSWORD }}" sftp -o StrictHostKeyChecking=no "${{ secrets.SFTP_USERNAME }}@ssh.strato.de" <<EOF
        cd /  # <-- Zielverzeichnis anpassen, falls nötig
        put -r * 
        bye
        EOF
