name: Deploy to Strato via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Upload files via SFTP (User 1)
      run: |
        sshpass -p 'zaxtewzamPyf1nunsa' sftp -o StrictHostKeyChecking=no sftp_GitHubDeploy@ssh.strato.de <<EOF
        put -r * 
        bye
        EOF

    # Fallback User 2 - Falls User 1 nicht klappt, kann man manuell diesen Schritt aktivieren
    # - name: Upload files via SFTP (User 2)
    #   run: |
    #     sshpass -p 'zaxtewzamPyf1nunsa' sftp -o StrictHostKeyChecking=no 5831011.swh.strato-hosting.eu@ssh.strato.de <<EOF
    #     put -r *
    #     bye
    #     EOF
