name: Test SCP Upload

on:
  push:
    branches:
      - main  # Oder dein Branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upload test file via SCP
        uses: appleboy/scp-action@master
        with:
          host: ssh.strato.de
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          source: "testfile.txt"
          target: "/htdocs/"   # Oder deinen echten Webroot
